theme: jekyll-theme-cayman
skin: dark
show_downloads: true
zip_url: https://github.com/alisahanyalcin/InfinityCore/archive/refs/heads/master.zip
another_url: https://github.com/alisahanyalcin/InfinityCore.git

title: InfinityCore 
description: InfinityCore is a PHP framework for building web applications.
